name: Pairio
options:
  bundleIdPrefix: com.loganallen
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_ENTITLEMENTS: Config/Pairio.entitlements
    PRODUCT_BUNDLE_IDENTIFIER: com.loganallen.Pairio
    INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

configs:
  Debug:
    xcconfig: Config/Debug.xcconfig
  Release:
    xcconfig: Config/Release.xcconfig

targets:
  Pairio:
    type: application
    platform: macOS
    sources:
      - path: Pairio
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: PairioPackage
        product: PairioFeature
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Pairio
        INFOPLIST_KEY_NSBluetoothAlwaysUsageDescription: "Pairio needs Bluetooth access to detect AirPods"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Pairio needs audio access to create multi-output devices"
        INFOPLIST_KEY_LSUIElement: YES

packages:
  PairioPackage:
    path: PairioPackage
